{{- include "aegra.validate" . }}
{{- if include "aegra.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegra.fullname" . }}
  labels:
    {{- include "aegra.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "aegra.secretData" . | nindent 2 }}
{{- end }}
